import json
import os
import google.genai as genai


# ==========================================================
# CONFIGURATION
# ==========================================================

def configure_gemini():
    api_key = "YOUR_API_KEY"

    if not api_key:
        print("Gemini API key not found.")
        print("Skipping AI summary.")
        print("To enable Gemini, set this in PowerShell:")
        print('$env:GEMINI_API_KEY="your_api_key_here"')
        return None

    try:
        client = genai.Client(api_key=api_key)
        return client
    except Exception as e:
        print(f"Failed to initialize Gemini: {e}")
        print("Skipping AI summary.")
        return None


# ==========================================================
# LOAD RECOMMENDATIONS
# ==========================================================

def load_recommendations():
    try:
        with open("recommended_laptops.json", "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        print("Error: recommended_laptops.json not found.")
        print("Run recommend.py first.")
        return None
    except Exception as e:
        print(f"Failed to load recommendations: {e}")
        return None


# ==========================================================
# BUILD PROMPT
# ==========================================================

def build_prompt(data):
    return f"""
You are given laptop recommendations generated by a benchmark-based recommendation engine.

Your task:
1. Briefly summarize each laptop in 3-5 bullet points.
2. Mention the main strengths and weaknesses.
3. Rank the laptops from best to worst.
4. Clearly state which laptop is the best overall choice.
5. Keep the response under 500 words.
6. Do NOT start with phrases like "As an expert laptop reviewer".
7. Be concise, practical, and honest.
8. Focus on:
   - battery life
   - portability
   - performance
   - build quality
   - software compatibility
   - value for money

If no_recommendations is true:
- Explain clearly why no laptops were found.
- Suggest realistic budget changes or requirement adjustments.
- Optionally suggest 2-3 alternative laptops within the budget.

If there are no recommendations:
- Suggest 2-3 good laptops in the same budget.

Recommendation Data:
{json.dumps(data, indent=2)}
"""

# ==========================================================
# GENERATE ANALYSIS
# ==========================================================

def generate_analysis():
    client = configure_gemini()
    if client is None:
        return

    data = load_recommendations()
    if data is None:
        return

    prompt = build_prompt(data)

    print("\nGenerating Gemini analysis...\n")

    try:
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        report = response.text.strip()
    except Exception as e:
        print(f"Gemini request failed: {e}")
        print("Skipping AI summary.")
        return

    print("=" * 70)
    print("GEMINI SUMMARY")
    print("=" * 70)
    print(report)

    try:
        with open("final_report.txt", "w", encoding="utf-8") as f:
            f.write(report)

        print("\nSaved analysis to final_report.txt")
    except Exception as e:
        print(f"Could not save final_report.txt: {e}")


# ==========================================================
# MAIN
# ==========================================================

if __name__ == "__main__":
    generate_analysis()